export const paintings = [
  {
    id: 1,
    painter: "Aurelia",
    imgSmall: "/images/disponibile/1/1.jpg",
    imgBig1: "/images/disponibile/1/1a.jpg",
    imgBig2: "/images/disponibile/1/1b.jpg",
    imgBig3: "/images/disponibile/1/1c.jpg",
    imgBig4: "/images/disponibile/1/1e.jpg",
    imgBig5: "/images/disponibile/1/1f.jpg",
    title: "Trei frati",
    description: "Tehnica: acrilic. Compoziție proprie",
    sizeCm: "60x40",
    price: 4000,
  },
  {
    id: 2,
    painter: "Aurelia",
    imgSmall: "/images/disponibile/2/2.jpg",
    imgBig1: "/images/disponibile/2/2a.jpg",
    imgBig2: "/images/disponibile/2/2b.jpg",
    imgBig3: "/images/disponibile/2/2c.jpg",
    imgBig4: "/images/disponibile/2/2e.jpg",
    imgBig5: "/images/disponibile/2/2f.jpg",
    title: "Dragoste",
    description:
      "Tehnica: acrilic. Reproducere după o compoziție accesibilă online. Autor interpretat",
    sizeCm: "50x70",
    price: 1500,
  },
  {
    id: 3,
    painter: "Aurelia",
    imgSmall: "/images/disponibile/3/3.jpg",
    imgBig1: "/images/disponibile/3/3a.jpg",
    imgBig2: "/images/disponibile/3/3b.jpg",
    imgBig3: "/images/disponibile/3/3c.jpg",
    title: "Balet si flori",
    description: "Tehnica: acrilic. Compoziție proprie",
    sizeCm: "70x50",
    price: 2000,
  },
  {
    id: 4,
    painter: "Aurelia",
    imgSmall: "/images/disponibile/4/4.jpg",
    imgBig1: "/images/disponibile/4/4a.jpg",
    imgBig2: "/images/disponibile/4/4b.jpg",
    imgBig3: "/images/disponibile/4/4c.jpg",
    title: "Diversitate",
    description: "Tehnica: acrilic. Compoziție proprie",
    sizeCm: "70x50",
    price: 2000,
  },
  {
    id: 5,
    painter: "Aurelia",
    imgSmall: "/images/disponibile/5/5.jpg",
    imgBig1: "/images/disponibile/5/5a.jpg",
    imgBig2: "/images/disponibile/5/5b.jpg",
    imgBig3: "/images/disponibile/5/5c.jpg",
    title: "Madame",
    description:
      "Tehnica: ulei. Reproducere după o compoziție accesibilă online. Autor interpretat",
    sizeCm: "25x25",
    price: 1000,
  },

  {
    id: 6,
    painter: "Cristina-Bontea",
    imgSmall: "/images/disponibile/6/6.jpg",
    imgBig1: "/images/disponibile/6/6a.jpg",
    imgBig2: "/images/disponibile/6/6b.jpg",
    title: "Tablou 20",
    description:
      "Vopsea acrilică pe pânză de sac. Tehnica mixtă, categorie abstract.",
    sizeCm: "195x90",
    price: 1000,
  },
  {
    id: 7,
    painter: "Cristina-Bontea",
    imgSmall: "/images/disponibile/7/7.png",
    imgBig1: "/images/disponibile/7/7a.png",
    imgBig2: "/images/disponibile/7/7b.png",
    title: "Tablou 21",
    description:
      "Vopsea acrilică pe pânză de sac. Tehnica mixtă, categorie abstract.",
    sizeCm: "145x90",
    price: 800,
  },
  {
    id: 8,
    painter: "Cristina-Bontea",
    imgSmall: "/images/disponibile/8/8.png",
    imgBig1: "/images/disponibile/8/8a.png",
    imgBig2: "/images/disponibile/8/8b.png",
    title: "Tablou 23",
    description:
      "Vopsea acrilică pe pânză de sac. Tehnica mixtă, categorie abstract.",
    sizeCm: "94x94",
    price: 2400,
  },
  {
    id: 9,
    painter: "Cristina-Bontea",
    imgSmall: "/images/disponibile/9/9.png",
    imgBig1: "/images/disponibile/9/9a.png",
    imgBig2: "/images/disponibile/9/9b.png",
    title: "Tablou 24",
    description:
      "Vopsea acrilică pe pânză de sac. Tehnica mixtă, categorie abstract.",
    sizeCm: "150x90",
    price: 3800,
  },
  {
    id: 10,
    painter: "Cristina-Bontea",
    imgSmall: "/images/disponibile/10/10.png",
    imgBig1: "/images/disponibile/10/10a.png",
    imgBig2: "/images/disponibile/10/10b.png",
    title: "Tablou 27",
    description:
      "Vopsea acrilică pe pânză de sac. Tehnica mixtă, categorie abstract.",
    sizeCm: "200x87",
    price: 2100,
  },
]
